Upgrade client for support API v2
jrwren/domasimu pull request #3
Opened 2018-10-06 22:38 UTC by pleum

Upgrade client for support API v2

2018-10-06 23:10 UTC, jrwren requested changes
This looks great! Huge Thanks To You.

2018-10-06 23:10 UTC, jrwren commented on cmd/domasimu/main.go
> +	"github.com/dnsimple/dnsimple-go/dnsimple"
Will you please update the .travis.yml to reflect this package change so that tests will fetch the right package?

2018-10-07 00:45 UTC, jrwren approved these changes

2018-10-07 06:24 UTC, pleum commented on cmd/domasimu/main.go
> +	"github.com/dnsimple/dnsimple-go/dnsimple"
Sure! 😁

2018-10-07 14:44 UTC, merged

2018-10-07 14:44 UTC, jrwren commented
HUGE thanks! This is great!